### ISSUE TITLE
Vps Reconnect were we left

### ISSUE THREAD

**Issue by STRK-ND** [dev-bon/ubuntu-docker-vps#1]
Hello Dev Bon, 
May I get the info, how to get in to vps again after the docker is Closed and open again with previous Container,

**Comment by dibonjohnseron** [comment]
Hello @STRK-ND, I may have missed this, to reconnect to the vps again, you could list all the running containers by doing
`docker ps` then you can use the `docker attach` command to reattach to the container ex. `docker attach <container_id_or_name>` or if you prefer to open a new shell in the same container instead of attaching, you can use the `docker exec` command ex. `docker exec -it <container_id_or_name> /bin/bash`
